import { INTERACTIVE_OBJECT_STYLES } from '@/app/constants/styles/interactiveObjects'
import type { LevelConfig } from '@/types/level'

export const finalLevel: LevelConfig = {
  id: 'level-6',
  title: 'Nucleo de Conservacion',
  background: '/backgrounds/final-level.png',
  character: 'nexus',
  introduction: [
    { speaker: 'KIRA', text: 'El movimiento ha sido restaurado.' },
    { speaker: 'VEGA', text: 'La gravedad vuelve a mantener el equilibrio.' },
    { speaker: 'LUMEN', text: 'La luz vuelve a iluminar el laboratorio.' },
    { speaker: 'VOLT', text: 'La electricidad vuelve a recorrer los sistemas.' },
    { speaker: 'NOVA', text: 'La energia quimica vuelve a alimentar la vida.' },
    { speaker: 'NEXUS', text: 'Han restaurado los sistemas...' },
    { speaker: 'NEXUS', text: 'pero el verdadero problema nunca fue la falta de energia.' },
    { speaker: 'NEXUS', text: 'El verdadero problema fueron las transformaciones.' },
    { speaker: 'NEXUS', text: 'Yo las detuve para evitar el desperdicio.' },
  ],
  completionDialogue: [
    { speaker: 'NEXUS', text: 'He cometido un error.' },
    { speaker: 'NEXUS', text: 'El equilibrio no consiste en detener los cambios.' },
    { speaker: 'NEXUS', text: 'Consiste en comprenderlos.' },
    { speaker: 'SISTEMA', text: 'NUCLEO RESTAURADO' },
    { speaker: 'SISTEMA', text: 'Todos los pilares energeticos estan activos.' },
    { speaker: 'KIRA', text: 'El laboratorio vuelve a moverse.' },
    { speaker: 'VEGA', text: 'La materia y la energia recuperan su equilibrio.' },
    { speaker: 'LUMEN', text: 'La luz vuelve a recorrer cada sala.' },
    { speaker: 'VOLT', text: 'Los sistemas se reinician.' },
    { speaker: 'NOVA', text: 'La naturaleza y la tecnologia vuelven a convivir.' },
    { speaker: 'SISTEMA', text: '¡FELICIDADES!' },
    { speaker: 'SISTEMA', text: 'Has obtenido el titulo de GUARDIAN DE LA CONSERVACION.' },
    { speaker: 'SISTEMA', text: 'El conocimiento cientifico es la herramienta mas poderosa para comprender el mundo.' },
  ],
  nextLevel: null,
  interactiveObjects: [
    {
      id: 'cascada-energia',
      type: 'interactive',
      title: 'Cascada de Energia',
      area: { x: 1, y: 15, width: 26, height: 78 },
      unlockAfter: null,
      activityId: 'activity-28',
      visual: {
        resource: '/assets/final-level/cascada.png',
        transform: 'perspective(1000px) rotateY(14deg) rotateZ(1deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
    {
      id: 'ecosistema-inteligente',
      type: 'interactive',
      title: 'Ecosistema Inteligente',
      area: { x: 23, y: 36, width: 18, height: 50 },
      unlockAfter: 'cascada-energia',
      activityId: 'activity-29',
      visual: {
        resource: '/assets/final-level/ecosistema.png',
        transform: 'perspective(1000px) translateY(-8px) scale(0.88) rotateZ(-1deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 0.9,
        className:
          `${INTERACTIVE_OBJECT_STYLES.hoverDefault} saturate-90 brightness-95 contrast-90 blur-[0.4px] drop-shadow-[0_8px_18px_rgba(0,0,0,0.12)]`,
      },
    },
    {
      id: 'laboratorio-transformaciones',
      type: 'interactive',
      title: 'Laboratorio de Transformaciones',
      area: { x: 60, y: 42, width: 18, height: 45 },
      unlockAfter: 'ecosistema-inteligente',
      activityId: 'activity-30',
      visual: {
        resource: '/assets/final-level/transformaciones.png',
        transform: 'perspective(1000px) rotateZ(-0.5deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
    {
      id: 'nexus-omega',
      type: 'interactive',
      title: 'NEXUS Ω',
      area: { x: 76, y: 9, width: 25, height: 86 },
      unlockAfter: 'laboratorio-transformaciones',
      activityId: 'activity-31',
      visual: {
        resource: '/assets/final-level/nexus-altar.png',
        transform: 'perspective(1200px) rotateZ(0.8deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
  ],
}
