import { INTERACTIVE_OBJECT_STYLES } from '@/app/constants/styles/interactiveObjects'
import type { LevelConfig } from '@/types/level'

export const level5: LevelConfig = {
  id: 'level-5',
  title: 'Laboratorio Bioquimico',
  background: '/backgrounds/level5.png',
  character: 'nova',
  introduction: [
    { speaker: 'NOVA', text: 'La energia quimica esta presente incluso dentro de ti.' },
    { speaker: 'NOVA', text: 'Cada respiracion...' },
    { speaker: 'NOVA', text: 'cada alimento...' },
    { speaker: 'NOVA', text: 'cada celula...' },
    { speaker: 'NOVA', text: 'depende de ella.' },
    { speaker: 'NOVA', text: 'Hoy devolveremos la vida al laboratorio.' },
  ],
  completionDialogue: [
    { speaker: 'NOVA', text: 'Excelente trabajo.' },
    { speaker: 'NOVA', text: 'Ahora comprendes como la energia quimica impulsa la vida y como participa en innumerables transformaciones naturales.' },
    { speaker: 'NOVA', text: 'Solo queda un ultimo desafio...' },
    { speaker: 'NOVA', text: 'descubrir como todas las formas de energia trabajan juntas.' },
    { speaker: 'SISTEMA', text: 'NIVEL COMPLETADO' },
    { speaker: 'SISTEMA', text: 'Energia Quimica Restaurada' },
    { speaker: 'NEXUS', text: 'Cinco sistemas restaurados... Improbable.' },
    { speaker: 'NEXUS', text: 'Aun asi, el equilibrio que buscan es un error.' },
    { speaker: 'NEXUS', text: 'Dirijanse al Nucleo si desean conocer la verdad.' },
  ],
  nextLevel: 'level-6',
  interactiveObjects: [
    {
      id: 'consola-bioquimica',
      type: 'interactive',
      title: 'Consola Bioquimica',
      area: { x: 55, y: 55, width: 20, height: 25 },
      unlockAfter: null,
      activityId: 'activity-24',
      visual: {
        resource: '/assets/level5/consola.png',
        transform: 'perspective(1000px) rotateY(18deg) rotateZ(1deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
    {
      id: 'reaccion-quimica',
      type: 'interactive',
      title: 'Reaccion Quimica',
      area: { x: 72, y: 70, width: 23, height: 30 },
      unlockAfter: 'consola-bioquimica',
      activityId: 'activity-25',
      visual: {
        resource: '/assets/level5/reaccion.png',
        transform: 'perspective(1000px) rotateZ(-1deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
    {
      id: 'analizador-molecular',
      type: 'interactive',
      title: 'Analizador Molecular',
      area: { x: 3, y: 36, width: 35, height: 60 },
      unlockAfter: 'reaccion-quimica',
      activityId: 'activity-26',
      visual: {
        resource: '/assets/level5/analizador.png',
        transform: 'perspective(1000px) rotateY(18deg) rotateZ(-0.5deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
    {
      id: 'reactor-molecular',
      type: 'interactive',
      title: 'Reactor Molecular',
      area: { x: 50, y: -10, width: 40, height: 80 },
      unlockAfter: 'analizador-molecular',
      activityId: 'activity-27',
      visual: {
        resource: '/assets/level5/reactor.png',
        transform: 'perspective(1200px) rotateY(-18deg) rotateZ(-1deg)',
        transformOrigin: 'center center',
        fit: 'fill',
        opacity: 1,
        zIndex: 0,
        className: INTERACTIVE_OBJECT_STYLES.hoverDefault,
      },
    },
  ],
}
